name: Wallpaper Generation

on: 
  push:
    branches:
      - main
  # schedule:
  #   - cron: ''
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Set up Python env
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - run: python image_generator.py
    # - name: Upload to Google Drive
    #   uses: logickoder/google-drive-upload@v2
    #   with:
    #     credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
    #     filename: "daily_wallpaper.jpg"
    #     folderID: ${{ secrets.GDRIVE_FOLDER_ID }}
    #     overwrite: "true" # Replaces the old file so your phone always sees the same filename
    # - name: Upload to Artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: wallpaper
    #     path: wallpaper.png
    #     compression-level: 0
    - run: |
        mkdir public
        mv wallpaper.png public/
        touch public/.nojekyll
        # Create a simple landing page so you can see it's working
        echo '<html><body><img src="wallpaper.png"></body></html>' > public/index.html
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
      with:
        path: public/
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Github pages
      id: deployment
      uses: actions/deploy-pages@v4 
